import React,{useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,ExternalLink} from 'lucide-react';
import './calendar-phase15.css';
const API=import.meta.env.VITE_API_URL||import.meta.env.VITE_API_BASE||'';
const BN=['জানুয়ারি','ফেব্রুয়ারি','মার্চ','এপ্রিল','মে','জুন','জুলাই','আগস্ট','সেপ্টেম্বর','অক্টোবর','নভেম্বর','ডিসেম্বর'],EN=['January','February','March','April','May','June','July','August','September','October','November','December'];
const DBN=['রবি','সোম','মঙ্গল','বুধ','বৃহ','শুক্র','শনি'],DEN=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export default function FiscalOfficeCalendar({lang='bn'}){
 const en=lang==='en',today=new Date(),[cursor,setCursor]=useState(new Date(today.getFullYear(),today.getMonth(),1)),[data,setData]=useState(null),[err,setErr]=useState('');
 useEffect(()=>{fetch(API+'/api/public/office-calendar?fy=2026-2027').then(r=>r.json()).then(x=>{if(x.error)throw new Error(x.error);setData(x)}).catch(e=>setErr(e.message))},[]);
 const hm=useMemo(()=>Object.fromEntries((data?.holidays||[]).map(x=>[x.holiday_date,x])),[data]);
 const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),last=new Date(cursor.getFullYear(),cursor.getMonth()+1,0),cells=[];
 for(let i=0;i<first.getDay();i++)cells.push(null);for(let d=1;d<=last.getDate();d++)cells.push(new Date(cursor.getFullYear(),cursor.getMonth(),d));
 const status=d=>{const h=hm[iso(d)];if(h)return['holiday',en?(h.title_en||h.title_bn):h.title_bn];if(d.getDay()===5||d.getDay()===6)return['weekend',en?'Weekly holiday':'সাপ্তাহিক ছুটি'];return['open',en?'Office open':'অফিস খোলা']};
 return <section className="fiscal-calendar" id="office-calendar"><div className="fc-head"><span>{en?'FISCAL-YEAR OFFICE CALENDAR':'অর্থবছরভিত্তিক অফিস ক্যালেন্ডার'}</span><h2>{en?'Office Open / Holiday Calendar 2026–2027':'অফিস খোলা / ছুটির ক্যালেন্ডার ২০২৬–২০২৭'}</h2><p>{en?'1 July 2026 to 30 June 2027. Friday, Saturday and listed office holidays are closed; every other day is open.':'১ জুলাই ২০২৬ থেকে ৩০ জুন ২০২৭। শুক্রবার, শনিবার ও তালিকাভুক্ত অফিস ছুটি বন্ধ; অন্য সব দিন অফিস খোলা।'}</p></div>{err&&<div className="fc-error">{err}</div>}<div className="fc-toolbar"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft/></button><b>{en?EN[cursor.getMonth()]:BN[cursor.getMonth()]} {cursor.getFullYear().toLocaleString(en?'en-US':'bn-BD',{useGrouping:false})}</b><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight/></button></div><div className="fc-week">{(en?DEN:DBN).map(x=><b key={x}>{x}</b>)}</div><div className="fc-grid">{cells.map((d,i)=>{if(!d)return <div className="fc-empty" key={'e'+i}/>;const [type,label]=status(d);return <div key={iso(d)} className={'fc-day '+type+(iso(d)===iso(today)?' today':'')}><strong>{d.getDate().toLocaleString(en?'en-US':'bn-BD')}</strong><small>{label}</small></div>})}</div><div className="fc-legend"><span><i className="open"/> {en?'Office open':'অফিস খোলা'}</span><span><i className="weekend"/> {en?'Friday / Saturday':'শুক্রবার / শনিবার'}</span><span><i className="holiday"/> {en?'Office holiday':'অফিস ছুটি'}</span></div><div className="fc-source"><div><b>{en?'Reference source':'রেফারেন্স উৎস'}</b><p>{en?'Published 2026–2027 holiday list; independent/unofficial reference.':'প্রকাশিত ২০২৬–২০২৭ ছুটির তালিকা; স্বাধীন/অনানুষ্ঠানিক রেফারেন্স।'}</p></div><a href={data?.source_url||'https://www.du.ac.bd/du_post_details/notice/27726'} target="_blank" rel="noreferrer">{en?'View source':'উৎস দেখুন'} <ExternalLink size={15}/></a></div></section>
}
