import React,{useEffect,useMemo,useState} from 'react';
import {BookOpen,Search,FileText,CalendarDays,Briefcase,WalletCards,Clock3,ShieldCheck,Download,Printer,LockKeyhole,RefreshCw,CheckCircle2,ExternalLink,Database,UserRound} from 'lucide-react';
import './final-core-phase16-19.css';

const API=import.meta.env.VITE_API_URL||import.meta.env.VITE_API_BASE||'';
async function req(path,opts={}){
  const r=await fetch(API+path,{credentials:'include',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});
  const d=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(d.error||d.detail||'Request failed');
  return d;
}
const dateFmt=(v,lang='bn')=>{
  if(!v)return '—';
  const d=new Date(String(v).length===10?`${v}T00:00:00`:v);
  if(isNaN(d))return String(v);
  return new Intl.DateTimeFormat(lang==='en'?'en-GB':'bn-BD',{day:'2-digit',month:'short',year:'numeric'}).format(d);
};
const n=(v,lang='bn',digits=0)=>Number(v||0).toLocaleString(lang==='en'?'en-US':'bn-BD',{maximumFractionDigits:digits});
function downloadJson(filename,data){
  const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'});
  const url=URL.createObjectURL(blob),a=document.createElement('a');
  a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);
}
function fiscalYear(){const d=new Date(),y=d.getFullYear();return d.getMonth()>=6?`${y}-${y+1}`:`${y-1}-${y}`;}

export function KnowledgeCenter({lang='bn'}){
  const en=lang==='en';
  const [notices,setNotices]=useState([]),[policies,setPolicies]=useState([]),[tab,setTab]=useState('all'),[q,setQ]=useState(''),[busy,setBusy]=useState(true),[err,setErr]=useState('');
  async function load(){setBusy(true);setErr('');try{const[a,b]=await Promise.all([req('/api/notices'),req('/api/policies')]);setNotices(a.notices||[]);setPolicies(b.policies||[])}catch(e){setErr(e.message)}finally{setBusy(false)}}
  useEffect(()=>{load()},[]);
  const rows=useMemo(()=>[...notices.map(x=>({...x,_type:'notice'})),...policies.map(x=>({...x,_type:'policy'}))].filter(x=>{
    if(tab!=='all'&&x._type!==tab)return false;const s=q.trim().toLowerCase();if(!s)return true;
    return [x.title_bn,x.title_en,x.summary_bn,x.summary_en,x.category,x.reference_no].some(v=>String(v||'').toLowerCase().includes(s));
  }).sort((a,b)=>String(b.publish_date||b.effective_date||b.created_at||'').localeCompare(String(a.publish_date||a.effective_date||a.created_at||''))),[notices,policies,tab,q]);
  return <div className="final-module"><section className="final-hero"><div><span>{en?'PHASE 16 · KNOWLEDGE CENTER':'ফেজ ১৬ · নলেজ সেন্টার'}</span><h2>{en?'Notices, Rules & Knowledge Center':'নোটিশ, বিধি ও নলেজ সেন্টার'}</h2><p>{en?'Search verified notices and policy references from one place.':'এক জায়গা থেকে যাচাইকৃত নোটিশ ও নীতিমালা/বিধির রেফারেন্স খুঁজুন।'}</p></div><BookOpen/></section>
    <div className="knowledge-tools"><div className="knowledge-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={en?'Search title, summary, category or reference...':'শিরোনাম, সারাংশ, ক্যাটাগরি বা রেফারেন্স খুঁজুন...'}/></div><div className="knowledge-tabs"><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>{en?'All':'সব'}</button><button className={tab==='notice'?'active':''} onClick={()=>setTab('notice')}>{en?'Notices':'নোটিশ'}</button><button className={tab==='policy'?'active':''} onClick={()=>setTab('policy')}>{en?'Policies / Rules':'নীতিমালা / বিধি'}</button><button onClick={load}><RefreshCw size={15}/></button></div></div>
    {err&&<div className="final-error">{err}</div>}{busy?<div className="final-empty">{en?'Loading...':'লোড হচ্ছে...'}</div>:rows.length===0?<div className="final-empty">{en?'No matching reference found.':'মিল পাওয়া যায়নি।'}</div>:<div className="knowledge-list">{rows.map(x=><article key={`${x._type}-${x.id}`}><div className={'knowledge-type '+x._type}>{x._type==='notice'?<CalendarDays/>:<BookOpen/>}<span>{x._type==='notice'?(en?'NOTICE':'নোটিশ'):(en?'POLICY / RULE':'নীতিমালা / বিধি')}</span></div><div className="knowledge-body"><small>{dateFmt(x.publish_date||x.effective_date||x.created_at,lang)}{x.category?` · ${x.category}`:''}</small><h3>{en?(x.title_en||x.title_bn):(x.title_bn||x.title_en)}</h3><p>{en?(x.summary_en||x.summary_bn||''):(x.summary_bn||x.summary_en||'')}</p>{x.reference_no&&<span className="reference-pill">{en?'Reference':'রেফারেন্স'}: {x.reference_no}</span>}</div>{x.file_url&&<a href={x.file_url} target="_blank" rel="noreferrer"><ExternalLink/></a>}</article>)}</div>}
    <div className="final-note"><ShieldCheck/><p>{en?'This center provides searchable reference information only. Always verify the applicable published rule/order before an official decision.':'এই কেন্দ্র শুধুমাত্র অনুসন্ধানযোগ্য রেফারেন্স তথ্য দেয়। অফিসিয়াল সিদ্ধান্তের আগে প্রযোজ্য প্রকাশিত বিধি/আদেশ যাচাই করুন।'}</p></div>
  </div>
}

export function PersonalCareerReports({lang='bn'}){
  const en=lang==='en';const[d,setD]=useState({career:null,salary:[],leave:[],calendar:null}),[busy,setBusy]=useState(true),[err,setErr]=useState('');
  async function load(){setBusy(true);setErr('');try{const fy=fiscalYear();const[career,salary,leave,calendar]=await Promise.all([req('/api/my-career'),req('/api/my-salary-history').catch(()=>({items:[]})),req('/api/my-leave-records').catch(()=>({items:[]})),req(`/api/public/office-calendar?fy=${encodeURIComponent(fy)}`).catch(()=>null)]);setD({career,salary:salary.items||[],leave:leave.items||[],calendar})}catch(e){setErr(e.message)}finally{setBusy(false)}}
  useEffect(()=>{load()},[]);const p=d.career?.profile||{},events=d.career?.events||[],edu=d.career?.education||[],totalLeave=d.leave.reduce((s,x)=>s+Number(x.total_days||x.days||0),0),latestSalary=d.salary[0]||null;
  const reportData={generated_at:new Date().toISOString(),career:d.career,salary_history:d.salary,leave_records:d.leave,office_calendar:d.calendar};
  return <div className="final-module report-module"><section className="final-hero"><div><span>{en?'PHASE 17 · PERSONAL REPORTS':'ফেজ ১৭ · ব্যক্তিগত রিপোর্ট'}</span><h2>{en?'Personal Career Reports':'ব্যক্তিগত ক্যারিয়ার রিপোর্ট'}</h2><p>{en?'A consolidated view of your own career, salary and leave records.':'নিজের চাকরি, বেতন ও ছুটির রেকর্ডের সমন্বিত সারসংক্ষেপ।'}</p></div><FileText/></section>
    {err&&<div className="final-error">{err}</div>}{busy?<div className="final-empty">{en?'Preparing report...':'রিপোর্ট প্রস্তুত হচ্ছে...'}</div>:<><div className="report-actions"><button onClick={()=>window.print()}><Printer/>{en?'Print / Save PDF':'প্রিন্ট / PDF সেভ'}</button><button onClick={()=>downloadJson(`my-career-data-${new Date().toISOString().slice(0,10)}.json`,reportData)}><Download/>{en?'Download Data JSON':'ডাটা JSON ডাউনলোড'}</button><button onClick={load}><RefreshCw/>{en?'Refresh':'রিফ্রেশ'}</button></div><section className="report-sheet"><div className="report-title"><small>{en?'Employee Digital Service Platform':'কর্মকর্তা-কর্মচারী ডিজিটাল সেবা'}</small><h1>{en?'Personal Career Summary':'ব্যক্তিগত ক্যারিয়ার সারসংক্ষেপ'}</h1><p>{en?'Generated':'প্রস্তুতের সময়'}: {new Date().toLocaleString(en?'en-GB':'bn-BD')}</p></div>
      <div className="report-kpis"><article><Briefcase/><small>{en?'Current Post':'বর্তমান পদ'}</small><b>{p.current_post||'—'}</b><span>{p.current_grade?`${en?'Grade':'গ্রেড'} ${n(p.current_grade,lang)}`:'—'}</span></article><article><CalendarDays/><small>{en?'Career Events':'ক্যারিয়ার ইভেন্ট'}</small><b>{n(events.length,lang)}</b><span>{en?'Saved records':'সংরক্ষিত রেকর্ড'}</span></article><article><WalletCards/><small>{en?'Salary Snapshots':'বেতন স্ন্যাপশট'}</small><b>{n(d.salary.length,lang)}</b><span>{latestSalary?`${en?'Net':'নিট'} ${n(latestSalary.net_salary,lang)}`:'—'}</span></article><article><Clock3/><small>{en?'Leave Recorded':'রেকর্ডকৃত ছুটি'}</small><b>{n(totalLeave,lang,1)}</b><span>{en?'day(s)':'দিন'}</span></article></div>
      <div className="report-sections"><section><h3>{en?'Career Profile':'চাকরি প্রোফাইল'}</h3><div className="report-grid"><span>{en?'First joining':'প্রথম যোগদান'}<b>{dateFmt(p.first_joining_date,lang)}</b></span><span>{en?'Current post joining':'বর্তমান পদে যোগদান'}<b>{dateFmt(p.current_post_joining_date,lang)}</b></span><span>{en?'Office / Unit':'অফিস / ইউনিট'}<b>{p.office_name||'—'}</b></span><span>{en?'Department':'বিভাগ / শাখা'}<b>{p.department_name||'—'}</b></span></div></section><section><h3>{en?'Education':'শিক্ষাগত যোগ্যতা'}</h3>{edu.length?edu.slice(0,6).map(x=><div className="report-row" key={x.id}><b>{x.level}</b><span>{[x.subject,x.institution,x.passing_year].filter(Boolean).join(' · ')}</span></div>):<p>—</p>}</section><section><h3>{en?'Recent Career Timeline':'সাম্প্রতিক ক্যারিয়ার টাইমলাইন'}</h3>{events.length?events.slice(0,8).map(x=><div className="report-row" key={x.id}><b>{dateFmt(x.event_date,lang)} · {x.title}</b><span>{[x.post_name,x.grade?`${en?'Grade':'গ্রেড'} ${x.grade}`:'',x.office_name].filter(Boolean).join(' · ')}</span></div>):<p>—</p>}</section></div><div className="report-disclaimer">{en?'Personal self-service report. It is not an official service book, salary fixation order, leave approval or promotion order.':'ব্যক্তিগত স্ব-সেবা রিপোর্ট। এটি অফিসিয়াল সার্ভিস বুক, বেতন নির্ধারণ আদেশ, ছুটি অনুমোদন বা পদোন্নতি আদেশ নয়।'}</div></section></>}
  </div>
}

export function PrivacyControlCenter({lang='bn'}){
  const en=lang==='en';const[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('');
  async function exportAll(){setBusy(true);setErr('');setMsg('');try{const fy=fiscalYear();const[me,career,salary,leave,calendar]=await Promise.all([req('/api/me'),req('/api/my-career'),req('/api/my-salary-history').catch(()=>({items:[]})),req('/api/my-leave-records').catch(()=>({items:[]})),req(`/api/public/office-calendar?fy=${fy}`).catch(()=>null)]);downloadJson(`my-platform-data-${new Date().toISOString().slice(0,10)}.json`,{exported_at:new Date().toISOString(),account:me.user,career,salary_history:salary.items||[],leave_records:leave.items||[],calendar_reference:calendar});setMsg(en?'Your personal data export has been created locally in your browser.':'আপনার ব্যক্তিগত ডাটা export ব্রাউজারেই তৈরি হয়েছে।')}catch(e){setErr(e.message)}finally{setBusy(false)}}
  async function logoutOthers(){setBusy(true);setErr('');setMsg('');try{await req('/api/my-security/logout-others',{method:'POST'});setMsg(en?'Other active sessions have been signed out.':'অন্যান্য সক্রিয় সেশন লগআউট করা হয়েছে।')}catch(e){setErr(e.message)}finally{setBusy(false)}}
  function clearVisitor(){localStorage.removeItem('public_visitor_id');setMsg(en?'Local anonymous visitor identifier cleared from this browser.':'এই ব্রাউজারের স্থানীয় anonymous visitor identifier মুছে ফেলা হয়েছে।')}
  return <div className="final-module"><section className="final-hero"><div><span>{en?'PHASE 18 · USER CONTROL & PRIVACY':'ফেজ ১৮ · ব্যবহারকারী নিয়ন্ত্রণ ও গোপনীয়তা'}</span><h2>{en?'My Data & Privacy':'আমার ডাটা ও গোপনীয়তা'}</h2><p>{en?'Export your own records and control browser/session privacy without an approval workflow.':'কোনো অনুমোদন প্রক্রিয়া ছাড়াই নিজের রেকর্ড export ও browser/session privacy নিয়ন্ত্রণ করুন।'}</p></div><LockKeyhole/></section>{err&&<div className="final-error">{err}</div>}{msg&&<div className="final-success">{msg}</div>}<div className="privacy-grid"><article><Database/><h3>{en?'Download My Data':'আমার ডাটা ডাউনলোড'}</h3><p>{en?'Creates a JSON copy of your account, personal career, salary and leave records in your browser.':'আপনার account, চাকরি, বেতন ও ছুটির রেকর্ডের JSON কপি ব্রাউজারে তৈরি করবে।'}</p><button onClick={exportAll} disabled={busy}><Download/>{en?'Export My Data':'আমার ডাটা Export'}</button></article><article><ShieldCheck/><h3>{en?'Sign Out Other Sessions':'অন্যান্য সেশন লগআউট'}</h3><p>{en?'Keeps this device signed in and invalidates your other active sessions.':'এই ডিভাইসটি লগইন রাখা হবে, অন্য সক্রিয় সেশনগুলো বন্ধ হবে।'}</p><button onClick={logoutOthers} disabled={busy}><LockKeyhole/>{en?'Sign Out Other Devices':'অন্য ডিভাইস লগআউট'}</button></article><article><UserRound/><h3>{en?'Reset Anonymous Visitor ID':'Anonymous Visitor ID মুছুন'}</h3><p>{en?'Removes the local anonymous public-visitor identifier stored only in this browser.':'শুধু এই ব্রাউজারে থাকা anonymous public-visitor identifier মুছে দেবে।'}</p><button onClick={clearVisitor}><RefreshCw/>{en?'Clear Local Identifier':'Local Identifier মুছুন'}</button></article></div><div className="final-note"><ShieldCheck/><p>{en?'The platform does not require paid email/SMS or a document vault for these controls. Sensitive passwords and recovery codes are never included in data exports.':'এই নিয়ন্ত্রণগুলোর জন্য paid email/SMS বা document vault প্রয়োজন নেই। Password ও recovery code কখনো data export-এ অন্তর্ভুক্ত হয় না।'}</p></div></div>
}

export function FinalReleaseStatus({lang='bn'}){
  const en=lang==='en';const rows=en?[['Self-service account & recovery','Ready'],['Personal career record','Ready'],['Promotion calculator','Ready'],['Salary/pay-scale calculator','Ready'],['Salary history','Ready'],['Leave record','Ready'],['Fiscal office calendar','Ready'],['Knowledge center','Ready'],['Personal reports','Ready'],['User control & privacy','Ready']]:[['স্ব-সেবা অ্যাকাউন্ট ও রিকভারি','প্রস্তুত'],['ব্যক্তিগত চাকরি রেকর্ড','প্রস্তুত'],['পদোন্নতি ক্যালকুলেটর','প্রস্তুত'],['বেতন/পে-স্কেল ক্যালকুলেটর','প্রস্তুত'],['বেতন ইতিহাস','প্রস্তুত'],['ছুটির হিসাব','প্রস্তুত'],['অর্থবছরভিত্তিক অফিস ক্যালেন্ডার','প্রস্তুত'],['নলেজ সেন্টার','প্রস্তুত'],['ব্যক্তিগত রিপোর্ট','প্রস্তুত'],['ব্যবহারকারী নিয়ন্ত্রণ ও গোপনীয়তা','প্রস্তুত']];
  return <div className="final-module"><section className="final-hero"><div><span>{en?'PHASE 19 · FREE PLATFORM OPTIMIZATION':'ফেজ ১৯ · ফ্রি প্ল্যাটফর্ম অপ্টিমাইজেশন'}</span><h2>{en?'Final Core Release Status':'ফাইনাল কোর রিলিজ স্ট্যাটাস'}</h2><p>{en?'Core functionality consolidated without adding paid infrastructure or changing verified salary/promotion formulas.':'Paid infrastructure না বাড়িয়ে এবং যাচাইকৃত বেতন/পদোন্নতি সূত্র না বদলে core functionality একত্র করা হয়েছে।'}</p></div><CheckCircle2/></section><div className="release-grid">{rows.map(([a,b])=><article key={a}><CheckCircle2/><span>{a}</span><b>{b}</b></article>)}</div><div className="optimization-box"><h3>{en?'Free-first operating model':'Free-first পরিচালনা নীতি'}</h3><p>{en?'Uses the existing Cloudflare Pages + Worker + D1 architecture, browser-generated reports/exports, no paid OTP provider, no document vault and bounded API requests.':'বিদ্যমান Cloudflare Pages + Worker + D1 architecture, browser-generated report/export, কোনো paid OTP provider নয়, document vault নয় এবং সীমিত API request ব্যবহার করা হয়েছে।'}</p></div></div>
}
